# Generated by Django 2.2.27 on 2022-05-04 21:00

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[user.models.validate_extension]),
        ),
    ]
