# Generated by Django 2.2.27 on 2022-04-25 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20220417_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Chat'),
        ),
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together={('user', 'chat')},
        ),
    ]
